//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFEmpleados.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class seccion
    {
        public seccion()
        {
            this.empleado = new HashSet<empleado>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public Nullable<decimal> SueldoMaximo { get; set; }
        public Nullable<int> TotalEmpleados { get; set; }
    
        public virtual ICollection<empleado> empleado { get; set; }
    }
}
